version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api/models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - survival-net

  web:
    build: ./web
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000/predict
    networks:
      - survival-net

networks:
  survival-net: